language: python

python:
  - "3.4.3"
  - "3.5"

services:
  - postgresql

install: "pip install -r requirements.txt"

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - psql -c 'create database fse_db;' -U postgres

script: python app_tests.py
deploy:
  provider: heroku
  api_key: 4c0de70c-1815-4b3c-bf52-6cf4c28cf46a
  app: uraniumreborn